### ISSUE TITLE
I was dumb and I need help

### ISSUE THREAD

**Issue by mrGlasses** [wimspaargaren/final-unit#14]
I installed final-unit before getting goimports, now every time I get: `time="19:03:33" level=fatal msg="go imports not found please install using: go get golang.org/x/tools/cmd/goimports"`, I've tried to delete the .exe file from bin and reinstall, can someone help me?

**Comment by wimspaargaren** [comment]
Hello @mrGlasses , I think the README is a bit outdated. Did you try to install it as follows:
```
go install golang.org/x/tools/cmd/goimports@latest
```

**Comment by mrGlasses** [comment]
Uhh, that works. Just for a note, I had to import the "github.com/stretchr/testify/suite" to my project to make it run, but thanks!
